/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "/Users/jkb/work/whatsapp/client/iphone/2_8_6//Users/jkb/Work/whatsapp/client/iphone/2_8_6/.h"

#import "DeleteAccountControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class ActivityLabel, UISwitch;

@interface AdvancedChatSettingsContoller : /Users/jkb/work/whatsapp/client/iphone/2_8_6//Users/jkb/Work/whatsapp/client/iphone/2_8_6/ <UINavigationControllerDelegate, DeleteAccountControllerDelegate>
{
    ActivityLabel *_activityLabel;
    UISwitch *_switchLastSeen;
    UISwitch *_switchAutoDownload;
    BOOL _showAutodownloadSection;
}

- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)lastSeenSettingFailedWithError:(id)fp8 userData:(id)fp12;
- (void)lastSeenSettingSet:(id)fp8;
- (void)delegateAccountContollerDidCancel:(id)fp8;
- (void)delegateAccountContollerDidFinish:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForFooterInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)switchAutoDownloadAction:(id)fp8;
- (void)switchLastSeenAction:(id)fp8;
- (void)showDeleteAccountPage;
- (void)hideActivity;
- (void)showActivity:(id)fp8;
- (void)dealloc;
- (id)init;

@end

